# make file to build mask program

PROGRAM = MASK_IOAPI
IOAPI = $(M3LIB)/ioapi
NETCDF = $(M3LIB)/netcdf

# Include file subsitution definitions
INCLUDES =  \

FC_FLAGS = -c -extend_source -I $(IOAPI)/include

FC=ifort

LIBRARIES = -L $(IOAPI)/lib -lioapi \
	    -L $(NETCDF)/lib -lnetcdf

OBJS = \
 $(PROGRAM).o


$(PROGRAM):  $(OBJS)
	$(FC) $(OBJS) $(LIBRARIES)  -o $(PROGRAM)

.F.o:
	$(FC) $(FC_FLAGS) $<


