#!/bin/csh -f
#> symlink the v5.2.1 Species Definition files

 set CMD = '/bin/ln -s'
 set src = ../../../../CCTM/src/MECHS

 $CMD $src/cb6r3_ae7_aq/SpecDef_cb6r3_ae7_aq.txt
 $CMD $src/cb6r3_ae7_aq/SpecDef_Conc_cb6r3_ae7_aq.txt
 $CMD $src/cb6r3_ae7_aq/SpecDef_Dep_cb6r3_ae7_aq.txt
 $CMD $src/cb6r5_ae7_aq/SpecDef_cb6r5_ae7_aq.txt
 $CMD $src/cb6r5_ae7_aq/SpecDef_Conc_cb6r5_ae7_aq.txt
 $CMD $src/cb6r5_ae7_aq/SpecDef_Dep_cb6r5_ae7_aq.txt
 $CMD $src/cb6r5hap_ae7_aq/SpecDef_cb6r5hap_ae7_aq.txt
 $CMD $src/cb6r5hap_ae7_aq/SpecDef_Conc_cb6r5hap_ae7_aq.txt
 $CMD $src/cb6r5hap_ae7_aq/SpecDef_Dep_cb6r5hap_ae7_aq.txt
 $CMD $src/cb6r5m_ae7_aq/SpecDef_cb6r5m_ae7_aq.txt
 $CMD $src/cb6r5m_ae7_aq/SpecDef_Conc_cb6r5m_ae7_aq.txt
 $CMD $src/cb6r5m_ae7_aq/SpecDef_Dep_cb6r5m_ae7_aq.txt
 
 $CMD $src/cracmm1amore_aq/SpecDef_cracmm1amore_aq.txt
 $CMD $src/cracmm1amore_aq/SpecDef_Conc_cracmm1amore_aq.txt
 $CMD $src/cracmm1amore_aq/SpecDef_Dep_cracmm1amore_aq.txt
 $CMD $src/cracmm1_aq/SpecDef_cracmm1_aq.txt
 $CMD $src/cracmm1_aq/SpecDef_Conc_cracmm1_aq.txt
 $CMD $src/cracmm1_aq/SpecDef_Dep_cracmm1_aq.txt
 $CMD $src/cracmm2/SpecDef_cracmm2.txt
 $CMD $src/cracmm2/SpecDef_Conc_cracmm2.txt
 $CMD $src/cracmm2/SpecDef_Dep_cracmm2.txt
 
 $CMD $src/racm2_ae6_aq/SpecDef_racm2_ae6_aq.txt
 $CMD $src/racm2_ae6_aq/SpecDef_Dep_racm2_ae6_aq.txt
 
 $CMD $src/saprc07tc_ae6_aq/SpecDef_saprc07tc_ae6_aq.txt
 $CMD $src/saprc07tc_ae6_aq/SpecDef_Dep_saprc07tc_ae6_aq.txt
 $CMD $src/saprc07tic_ae7i_aq/SpecDef_saprc07tic_ae7i_aq.txt
 $CMD $src/saprc07tic_ae7i_aq/SpecDef_Dep_saprc07tic_ae7i_aq.txt
