#! /bin/csh -f
# C-shell script to run CR_EBI_SOLVER 

 date; set timestamp; set echo 

 set BASE            = $cwd
 set STEM            = $BASE
 set EXDIR           = ${BASE}/BLD  
 set EXEC            = cr_ebi_solver 

#> option to set compiler and build a new executable (not required)
 setenv COMPILER  GFORT  #> INTEL, PGF90, or GFORT
 if( ${COMPILER} == "GFORT")then
      setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/share/linux86_64/gcc-4.9.3/lib64
 endif

#> Define the gas, aerosol and aqueous components in MECHNAME
#> GC_NAME Options: CB6R3, CB05MP51, CB05E51, CB05MP51, CB05TUCL, CB05TUMP, SAPRC07TB, SAPRC07TC, SAPRC07TIC, RACM2
#> AE_NAME Options: AE6, AE6I
#> AQ_NAME Options: AQ
 setenv GC_NAME       CB6r3
# setenv GC_NAME       CB05TUCL
#setenv GC_NAME       SAPRC16D
#setenv GC_NAME       SAPRC07TC
 setenv AE_NAME       AE6
 setenv AQ_NAME       AQ

 set MECH = ` echo ${GC_NAME}_${AE_NAME}_${AQ_NAME} |  tr 'a-zA-Z' 'A-Za-z' `
 set MECH = ` echo ${GC_NAME}_${AE_NAME}_${AQ_NAME} |  tr 'A-Z' 'a-z' `
 echo $MECH 
#set MECH = ${GC_NAME}_${AE_NAME}_${AQ_NAME}
#set MECH = sparc16d_ae6_aq

#set REP  = ${BASE}/input/${MECH}
#set REP  = /home/bhutzell/CCTM_git_repository/CCTM/src/MECHS/${MECH}
 set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/cb6r3_ae6_aq-Aug-28-2018-INTEL_mod2
#set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/cb6r3_ae6_aq-Jun-01-2018-INTEL_mod2
#set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/cb6r3_ae6_aq-Jan-04-2018-INTEL_mod2
#set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/saprc07tb_ae6_aq-Apr-05-2018-INTEL_mod2
#set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/saprc16d_ae6_aq-Mar-23-2018-GFORT_mod2
#set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/saprc16e_ae6_aq-Apr-05-2018-INTEL_mod2
#set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/saprc07tb_ae6_aq-Apr-05-2018-INTEL_mod2
#set REP  = /home/bhutzell/CCTM_git_repository/UTIL/chemmech/output/cb6r3_ae6_aq-Apr-06-2018-INTEL_mod2

#uses CMAQ version 5.1 of these include files for chemical mechanism
 setenv RXNS_DATA_SRC  ${REP}/RXNS_DATA_MODULE.F90

if ( ! ( -e ${RXNS_DATA_SRC} ) )then
       \ls ${RXNS_DATA_SRC}
       exit()
 endif 

# using templates for CMAQ version 5.0 
 setenv TMPLDIR         ${STEM}/template_RXNSU_OPT
 setenv DEGRADE_CODES   ${STEM}/degrade_codes_serial-RXNST
 setenv SRCDIR          ${STEM}/src_RXNSU

# output directory
 set day = ` date "+%b-%d-%Y" `
 setenv OUTDIR  ${BASE}/output/ebi_${MECH}-${day}-${COMPILER}_exp
 
 setenv COPYRT_FLAG      N
 setenv CVS_HDR_FLAG     N

 setenv ALL_MECHS       F    # obsolete option 
 setenv PAR_NEG_FLAG    T    # True for CB4 and CB05 but false for SAPRC07t and RACM2 
 setenv DEGRADE_SUBS    T    # include calls for HAPs degrade routines (true cb05tump and cb05mp51)
# below option is a possible solution based on work by Golam Sawar if the 
# mechanism includes excited NO2.  The user employs it at their own risk 
# and should check the EBI solver's accuracy against the Gear or Rosenbrock solver
 setenv NO2EX_CYCLE     F    # modify group one solution to include excited NO2
 setenv SOLVER_DELT     2.5  # maximum time step of solver integration up to four significant figures
                             # in general or scientific notation, units are minutes
  

#Set the below compound names within the mechanism
# Mechanism                  SAPRC99 or        CB4
#                         # SAPRC07 / RACM2  #  CB05 or cb6r3   #
 setenv MECH_NO    NO     #  NO           # NO       # Mechanism name for nitric oxide
 setenv MECH_NO2   NO2    #  NO2          # NO2      # Mechanism name for nitrogen dioxide
 setenv MECH_NO2EX NO2EX  #  NO2EX / Not Present # NO2S     # Mechanism name for excited nitrogen dioxide
 setenv MECH_O3    O3     #  O3           # O3       # Mechanism name for ozone
 setenv MECH_O3P   O     #  O3P          # O        # Mechanism name for ground state oxygen atom
#setenv MECH_O3P   O3P     #  O3P          # O        # Mechanism name for ground state oxygen atom
 setenv MECH_O1D   O1D    #  O1D2 or O1D  # O1D      # Mechanism name for excited state oxygen atom
 setenv MECH_OH    OH     #  HO or OH / HO  # OH       # Mechanism name for hydroxyl radical
 setenv MECH_HO2   HO2    #  HO2          # HO2      # Mechanism name for hydroperoxy radical
 setenv MECH_HONO  HONO   #  HONO         # HONO     # Mechanism name for nitrous acid
 setenv MECH_HNO4  PNA   #  HNO4         # PNA      # Mechanism name for peroxynitric acid
#setenv MECH_HNO4  HNO4   #  HNO4         # PNA      # Mechanism name for peroxynitric acid
 setenv MECH_PAN   PAN    #  PAN          # PAN      # Mechanism name for peroxy acetyl nitrate
 setenv MECH_C2O3  C2O3   #CCO_O2 or MECO3 / ACO3 # C2O3    # Mechanism name for peroxy acetyl radical
#setenv MECH_C2O3  MECO3  #CCO_O2 or MECO3 # C2O3    # Mechanism name for peroxy acetyl radical
 setenv MECH_NO3   NO3    #   NO3         # NO3      # Mechanism name for nitrate radical
 setenv MECH_N2O5  N2O5   #   N2O5        # N2O5     # Mechanism name for dinitrogen pentoxide
 
 rm cr_ebi_solver

#########################################################
 unalias rm

 if( -e ./BLD ) then
    echo "Removing old BLD directory"
    /bin/rm -rf ./BLD
 endif

 mkdir BLD

 cp makefile.v50XX  ./BLD/Makefile

 cd BLD

 make

 cd ..
 
set echo
##########################################################

 if(  -e $OUTDIR  ) then

    echo "Removing old solver files"
    /bin/rm -f ${OUTDIR}/*.[f,F]

 else

   mkdir -p $OUTDIR
   \cp -f ${RXNS_DATA_SRC} $OUTDIR/.

 endif

 $EXDIR/$EXEC

 if( $DEGRADE_SUBS  == "T" )then
     \cp -f ${DEGRADE_CODES}/*.[f,F]  ${OUTDIR}/.
 endif

 exit() 
