#!/bin/csh

set IOAPI_exist = `env | grep IOAPI | wc -l`
if (! $IOAPI_exist) then
   echo ' '
   echo ' Please setup the path for IOAPI library first and execute this script again'
   echo ' '
   echo '    e.g. setenv IOAPI /home/wdx/lib/x86_64/ifc-17.0.3/ioapi_3.1'
   echo ' '
   exit
endif

# type fmm -h for help
set exist_h = ` echo $argv | grep -e "-h" | wc -w `

if ($exist_h != 0) then
   goto usage
else
   goto checkarg
endif

cont:

if (! $create_makefile_only) then
# modify code in wrf
  cd wrfcmaq_twoway_coupler

  if (-d misc/orig) then
     rm -f -r misc/orig
  endif

  ls -1 */* > __tfile

  set count = `wc -l __tfile`

  @ n = 0

# copy twoway related files to the appropriate directory and keep an old copy
  while ($n < $count[1])
    @ n++
    set temp = `head -n $n __tfile | tail -n 1 | sed 's/\// /' `
    set directory = $temp[1]
    set file      = $temp[2]
    if (($directory != misc) && ($directory != script)) then
       if ($directory == external) then
          cp -p $directory/$file ../$directory/io_netcdf
       else
          if (-f ../$directory/$file) then
             if (! -d misc/orig) then
                mkdir misc/orig
             endif
             if (! -d misc/orig/$directory) then
              mkdir misc/orig/$directory
             endif
           mv ../$directory/$file misc/orig/$directory/$file
          endif
          cp -p $directory/$file ../$directory
       endif
    endif
  end

  rm -f __tfile

  mv ../clean misc/orig/clean
  cp -r clean ..

  mv ../Makefile misc/orig/Makefile
  cp -r Makefile ..

  cd ..

  cp cmaq/complex_number_module.F90 phys/complex_number_module.F
endif

# create Makefile.twoway

cd cmaq

if (-f mpif.h) then
   rm -f mpif.h
endif

cd ..

set found_openmpi = `echo $LD_LIBRARY_PATH | grep openmpi  | wc -l `

set tline = `grep "FORMAT_FIXED    =" configure.wrf`
if (`echo $tline | grep form | wc -l `) then
   set compiler = gcc
else if (`echo $tline | grep Mfixed | wc -l `) then
   set compiler = pgi
else if (`echo $tline | grep FI | wc -l `) then
   set compiler = ifort
   if ($found_openmpi) then
      cat configure.wrf | sed 's/=       mpif90 -f90=/=       mpifort -f90=/' > __new
   else
      cat configure.wrf | sed 's/=       mpif90 -f90=/=       mpiifort -f90=/' > __new
   endif
   mv __new configure.wrf
else
   echo 'ABORT: Unknow compiler '
   exit
endif

if (! $create_makefile_only) then
# modify configure.wrf
  wrfcmaq_twoway_coupler/reconfigure
endif

exit

#---------------------------------------------------------------------
checkarg:

set count = $#argv
if ($count == 1) then
   set create_makefile_only = 1
else
   set create_makefile_only = 0
endif

goto cont

# -------------------------------------------------------------------------
usage:
echo ' '
echo ' assemble [ m ] '
echo ' '
echo '    where option m to instruct the process to produce Makefile.twoway'
echo '      in cmaq only'
echo ' '
echo ' If you have any comment/question/problem using this script/program, '
echo ' please contact David Wong at wong.david-c@epa.gov'
echo ' '

exit

